#ifndef SMRU_APP_IDENTITY_H
#define SMRU_APP_IDENTITY_H
// SmackMyRezUp product identity - the one place that names things.
//
// Everything user-visible that carries the product's name (executables, the
// settings and log files, window classes, environment variables, the exporter's
// stderr tag and --serve banner, sidecar and export suffixes) is defined here so
// the player, the exporter and the resource scripts can never drift apart.
//
// The file is shared with the resource compiler: only preprocessor macros live
// above the RC_INVOKED guard; the C++ constants below it wrap those macros.

#include "SmackMyRezUpVersion.h"   // generated by CMake from src/Version.h.in

#define SMRU_PRODUCT_NAME   "SmackMyRezUp"
#define SMRU_COMPANY_NAME   "dagthomas"
#define SMRU_COPYRIGHT      "Copyright (c) 2026 dagthomas. MIT License."
#define SMRU_PLAYER_EXE     "SmackMyRezUp.exe"
#define SMRU_EXPORTER_NAME  "SmackMyRezUpExport"
#define SMRU_EXPORTER_EXE   "SmackMyRezUpExport.exe"

// stderr tag every exporter line starts with; the player's progress parser keys
// off "<tag> frame N".
#define SMRU_LOG_TAG        "[smru]"
// First line the exporter writes in --serve mode so a host can confirm it is
// talking to a compatible build.
#define SMRU_SERVE_BANNER   "SMRU-SERVE 1"

#ifndef RC_INVOKED
namespace smru {

// Wide and narrow spellings of the same names. A plain literal placed next to
// an L"" literal takes the wide prefix, so the macros above are reused verbatim.
inline constexpr const wchar_t* kProductNameW  = L"" SMRU_PRODUCT_NAME;
inline constexpr const char*    kProductName   = SMRU_PRODUCT_NAME;
inline constexpr const wchar_t* kVersionW      = L"" SMRU_VERSION_TEXT;
inline constexpr const char*    kVersion       = SMRU_VERSION_TEXT;
inline constexpr const wchar_t* kExporterNameW = L"" SMRU_EXPORTER_NAME;
inline constexpr const wchar_t* kExporterExeW  = L"" SMRU_EXPORTER_EXE;

// Files the executables create beside themselves or in their working directory.
inline constexpr const wchar_t* kSettingsFile     = L"SmackMyRezUp.ini";
inline constexpr const wchar_t* kModelsDir       = L"models";   // downloaded weights, beside the exe
inline constexpr const char*    kPlayerLogFile    = "SmackMyRezUp.log";
inline constexpr const wchar_t* kPlayerLogFileW   = L"SmackMyRezUp.log";
inline constexpr const char*    kExporterLogFile  = "SmackMyRezUpExport.log";
inline constexpr const wchar_t* kExporterLogFileW = L"SmackMyRezUpExport.log";

// Settings file layout ([section] names). kLegacySettingsSection is read as a
// fallback so values written by older builds carry over on first launch.
inline constexpr const wchar_t* kSettingsSection       = L"SmackMyRezUp";
inline constexpr const wchar_t* kLegacySettingsSection = L"DLSS";
inline constexpr const wchar_t* kAdjustmentsSection    = L"VideoAdjustments";
inline constexpr const wchar_t* kGeneralSection        = L"General";
inline constexpr const wchar_t* kToolsSection          = L"Tools";
inline constexpr const wchar_t* kToolsPythonKey        = L"Python";

// Environment variables honoured by the player and the Python tools.
inline constexpr const wchar_t* kEnvPython   = L"SMRU_PYTHON";      // interpreter for the tools folder scripts
inline constexpr const wchar_t* kEnvToolsDir = L"SMRU_TOOLS_DIR";   // folder holding the Python tools
inline constexpr const wchar_t* kEnvBinDir   = L"SMRU_BIN_DIR";     // ffmpeg/ffprobe/exporter folder (exported to children)
inline constexpr const wchar_t* kEnvComfyDir = L"SMRU_COMFYUI_DIR"; // ComfyUI portable root (holds python_embeded)
inline constexpr const wchar_t* kEnvModelsDir = L"SMRU_MODELS_DIR"; // where the Python tools cache model weights

// Win32 window classes.
inline constexpr const wchar_t* kWndClassMain          = L"SmackMyRezUp.MainWindow";
inline constexpr const wchar_t* kWndClassViewport      = L"SmackMyRezUp.Viewport";
inline constexpr const wchar_t* kWndClassRenderSurface = L"SmackMyRezUp.RenderSurface";
inline constexpr const wchar_t* kWndClassExportHidden  = L"SmackMyRezUp.ExportHidden";

// Sidecars generated beside a movie and attached automatically.
inline constexpr const wchar_t* kSidecarFlowSuffix  = L"_flow.mp4";
inline constexpr const wchar_t* kSidecarDepthSuffix = L"_depth.mp4";
inline constexpr const wchar_t* kSidecarMaskSuffix  = L"_mask.mp4";
inline constexpr const wchar_t* kSidecarSvrSuffix   = L"_svr.mp4";

// Default export names: <stem>_rezup[_<kind>].mp4
inline constexpr const wchar_t* kExportSuffix        = L"_rezup.mp4";
inline constexpr const wchar_t* kExportCompareSuffix = L"_rezup_compare.mp4";
inline constexpr const wchar_t* kExport4KSuffix      = L"_rezup_4k.mp4";
inline constexpr const wchar_t* kExportSplitSuffix   = L"_rezup_split.mp4";
inline constexpr const wchar_t* kSnapshotInfix       = L"_shot_";

// Labels stamped into compare/split outputs (glyphs live in LabelStamp.h).
inline constexpr const char* kLabelOriginal  = "ORIGINAL";
inline constexpr const char* kLabelProcessed = "SMACKMYREZUP";

// File names of the Python tools the player can launch.
inline constexpr const wchar_t* kToolFlowScript   = L"make_flow_video.py";
inline constexpr const wchar_t* kToolDepthScript  = L"make_depth_video.py";
inline constexpr const wchar_t* kToolSeedVRScript = L"run_seedvr.py";
inline constexpr const wchar_t* kToolMaskScript   = L"make_mask_video.py";

} // namespace smru
#endif // RC_INVOKED

#endif // SMRU_APP_IDENTITY_H
